version: '3'

services:
  server:
    build:
      context: .
    restart: "unless-stopped"
    #~ command: "tail -f /dev/null"
    command: "npm run world"
    working_dir: /app
    ports:
      - "62342:62342"
    volumes:
      - ".:/app"
