version: '3'

services:
  server:
    image: node
    restart: "unless-stopped"
    #~ command: "node server.js"
    command: "npm run world"
    working_dir: /app
    ports:
      - "62342:62342"
    volumes:
      - ".:/app"
